#ifndef CONSTANTS_H
#define CONSTANTS_H

#define LIST_INITIALIZER {NULL, NULL}
#define CSV_LINE_BUFFER_SIZE 1024
#define CSV_COLUMNS_COUNT 7
#define CSV_HEADER_SKIP 1
#define PARSE_SUCCESS 0
#define PARSE_ERROR -1
#define COMPARE_LESS -1
#define COMPARE_EQUAL 0
#define COMPARE_GREATER 1

enum ColumnIndex {
    COLUMN_YEAR = 0,
    COLUMN_REGION,
    COLUMN_NATURAL_GROWTH,
    COLUMN_BIRTH_RATE,
    COLUMN_DEATH_RATE,
    COLUMN_DEMO_WEIGHT,
    COLUMN_URBANIZATION
};

#endif // CONSTANTS_H
